services:
  aigun-server:
    network_mode: bridge
    container_name: aigun-server
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --log-level info
    mem_limit: 1G
    restart: always
